# Form implementation generated from reading ui file 'hand_layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HandWidget(object):
    def setupUi(self, HandWidget):
        HandWidget.setObjectName("HandWidget")
        HandWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(HandWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.drawButton = QtWidgets.QPushButton(parent=HandWidget)
        self.drawButton.setObjectName("drawButton")
        self.verticalLayout.addWidget(self.drawButton)

        self.retranslateUi(HandWidget)
        QtCore.QMetaObject.connectSlotsByName(HandWidget)

    def retranslateUi(self, HandWidget):
        _translate = QtCore.QCoreApplication.translate
        self.drawButton.setText(_translate("HandWidget", "Draw"))
