# Form implementation generated from reading ui file 'bang_ground.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bang_Ground(object):
    def setupUi(self, Bang_Ground):
        Bang_Ground.setObjectName("Bang_Ground")
        Bang_Ground.resize(751, 562)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Bang_Ground)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 732, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hpLayout = QtWidgets.QHBoxLayout()
        self.hpLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.hpLayout.setObjectName("hpLayout")
        self.hpLabel1 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.hpLabel1.setMaximumSize(QtCore.QSize(100, 60))
        self.hpLabel1.setText("")
        self.hpLabel1.setScaledContents(True)
        self.hpLabel1.setObjectName("hpLabel1")
        self.hpLayout.addWidget(self.hpLabel1)
        self.hpLabel2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.hpLabel2.setMaximumSize(QtCore.QSize(100, 60))
        self.hpLabel2.setText("")
        self.hpLabel2.setScaledContents(True)
        self.hpLabel2.setObjectName("hpLabel2")
        self.hpLayout.addWidget(self.hpLabel2)
        self.hpLabel3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.hpLabel3.setMaximumSize(QtCore.QSize(100, 60))
        self.hpLabel3.setText("")
        self.hpLabel3.setScaledContents(True)
        self.hpLabel3.setObjectName("hpLabel3")
        self.hpLayout.addWidget(self.hpLabel3)
        self.hpLabel4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.hpLabel4.setMaximumSize(QtCore.QSize(100, 60))
        self.hpLabel4.setText("")
        self.hpLabel4.setScaledContents(True)
        self.hpLabel4.setObjectName("hpLabel4")
        self.hpLayout.addWidget(self.hpLabel4)
        self.hpLabel5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.hpLabel5.setMaximumSize(QtCore.QSize(100, 60))
        self.hpLabel5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.hpLabel5.setText("")
        self.hpLabel5.setScaledContents(True)
        self.hpLabel5.setObjectName("hpLabel5")
        self.hpLayout.addWidget(self.hpLabel5)
        self.verticalLayout.addLayout(self.hpLayout)
        self.charequipLayout = QtWidgets.QHBoxLayout()
        self.charequipLayout.setObjectName("charequipLayout")
        self.charLayout = QtWidgets.QHBoxLayout()
        self.charLayout.setObjectName("charLayout")
        self.charequipLayout.addLayout(self.charLayout)
        self.equipLayout = QtWidgets.QHBoxLayout()
        self.equipLayout.setObjectName("equipLayout")
        self.charequipLayout.addLayout(self.equipLayout)
        self.charequipLayout.setStretch(0, 1)
        self.charequipLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.charequipLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)

        self.retranslateUi(Bang_Ground)
        QtCore.QMetaObject.connectSlotsByName(Bang_Ground)

    def retranslateUi(self, Bang_Ground):
        _translate = QtCore.QCoreApplication.translate
        Bang_Ground.setWindowTitle(_translate("Bang_Ground", "Form"))
